import type { MetadataRoute } from 'next'
 
export default function sitemap(): MetadataRoute.Sitemap {
  return[
    {
        url: "https://ratsms.com/",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 1,
    },
    {
        url: "https://ratsms.com/about-us",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.9,
    },
    {
        url: "https://ratsms.com/blog",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.9,
    },
    {
        url: "https://ratsms.com/bulk-sms",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.8,
    },
    {
        url: "https://ratsms.com/bulk-sms-gateway-aggregator",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.8,
    },
    {
        url: "https://ratsms.com/bulk-sms-pricing-india",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.7,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-explicit",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.7,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-implicit",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.7,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-ahmedabad",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-alappuzha",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-amaravati",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-bangalore",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-banjara-hills",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-coimbatore",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-delhi",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-ernakulam",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-gujarat",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-guwahati",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-hitec-city",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    }, {
        url: "https://ratsms.com/bulk-sms-service-provider-in-hyderabad ",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-indore",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-jaipur",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-jubilee-hills",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-kochi",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-kolkata",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-kollam",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-kottayam",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-kozhikode",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-kurnool",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-lucknow",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-madurai",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-mumbai",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
     {
        url: "https://ratsms.com/bulk-sms-service-provider-in-nagpur",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-noida",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-palakkad",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-patna",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-pune",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-raipur",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-surat",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-trivandrum",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-thrissur",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-vadodara",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/bulk-sms-service-provider-in-visakhapatnam",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/careers",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/careers/join-us/1",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/careers/join-us/2",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/careers/join-us/3",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/contact",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/developer-api",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/otp-bulk-sms-chennai",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/privacy-policy",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/promotional-bulk-sms-chennai",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/refund-policy",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/smartsms-send-bulk-sms-attachments",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/smpp-gateway-provider",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/smpp-gateway-provider",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/terms-and-conditions",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
    {
        url: "https://ratsms.com/transactional-bulk-sms-chennai",
        lastModified: new Date(),
        changeFrequency: "daily",
        priority: 0.6,
    },
  
    
]
}